### PR TITLE
Added Curtain thing + cleanup

### PR DESCRIPTION
**Pull request by kubawolanin**
* Replaced @dimalo's nick to real name in @author tags ;)
* Corrected items/rules/sitemap headings in README
* Improved README with supported devices 
* Added example ringtone rule
* Formatted things definitions
* Moved `batteryLevel` and `voltage` to `channels.xml`
* Corrected a few code review remarks from @martinvw
* Added a Curtain thing

TODO:

- Add a note in the README that your router must support multicast traffic from LAN to WLAN
- Change mV to V in battery voltage
- Add @octa22 to the authors list (since @pboos used EncryptionHelper.java from his 1.x binding)
- Add a Gas Sensor
- Add a Smoke Sensor
- Add the binding to the feature.xml
- ???

***I didn't test if the binding works, thus the WIP flag!***
This PR allows edits from maintainers, so feel free to add more stuff :)

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by dimalo** [comment]
Nice work @kubawolanin!

a few things I noticed - at the moment I am quite limited in time though...

- [x] Rename Sw1 & Sw2 channels, to clear confusion Switch vs trigger
- [x] Redo battery and voltage channels to be in line with ESH definition (see ESH docs) - means they should not be needed as there are generic ones, but for these the calculation should be changed (0%-100% instead of V)

All in all I appreciate, that somebody is pushing forward!
Only problem is, I cannot edit the PR, only @pboos can - who still should be waiting for his items to arrive. So if I find the time I can cherry pick your commit and refine further. Then I only can imagine I open a PR to your repo and you can add it to this PR then?

@pboos won't be able to take this WIP PR into his repo (at least not master), because then the marketplace version of the binding would be recompiled to a possibly not working one 🙅‍♂️  - this branch is directly connected to the openhab-PR...

**Comment by pboos** [comment]
@dimalo ok. I will wait on this one in that case, until you give me the go to merge :)

**Comment by martinvw** [comment]
Note that the Astro binding was removed, moved to eclipse smart home. So that might have been the reason for the conflict

**Comment by dimalo** [comment]
so @kubawolanin how is the first feedback? should we progress and merge into the OH PR to get the marketplace version?

**Comment by kubawolanin** [comment]
@dimalo not yet. I struggle with free time lastly, I should be able to test it with wireless switches etc. on the weekend.
Thank you!

**Comment by kubawolanin** [comment]
@dimalo, thank you so much for your hard work! Everything works as expected.
Here's the compiled JAR (09.06.2017) for anyone interested: 
[org.openhab.binding.mihome-2.1.0-SNAPSHOT.jar.zip](https://github.com/carecon/openhab2-addons/files/1064831/org.openhab.binding.mihome-2.1.0-SNAPSHOT.jar.zip)


### Remarks:

1. I'm not able to switch the wireless switch with an item ;-)

test.items:
```
Switch SomeTestSwitch "Mute" { channel="mihome:86sw2:158d0001XXXXXX:ch1" }
```

log:
```
2017-06-09 19:32:36.240 [WARN ] [home.handler.XiaomiSensorBaseHandler] - Channel mihome:86sw2:158d0001XXXXXX:ch1 does not exist
```

It's not stated in the documentation and I'm not sure how feasible this is to control the wireless switch now.
But it's worth exploring.


2. It's worth noting that you can actually create the `xiaomi.things` file:

#### xiaomi.things
```
Bridge mihome:bridge:f0b429XXXXXX "Xiaomi Gateway" [ serialNumber="f0b429XXXXXX", ipAddress="192.168.0.3", port=9898, key="XXXXXXXXXXXXXXXX", pollingInterval=6000 ] {
    Thing mihome:gateway:f0b429XXXXXX "Xiaomi Mi Smart Home Gateway" [itemId="f0b429XXXXXX"]

    Thing mihome:86sw2:158d0001XXXXXX "Aqara Wireless Wall Switch" [itemId="158d0001XXXXXX"]

    Thing mihome:sensor_switch:158d0001XXXXXX "Xiaomi Mi Wireless Switch" [itemId="158d0001XXXXXX"]

    Thing mihome:sensor_magnet:158d0001XXXXXX "Bedroom Door" [itemId="158d0001XXXXXX"]

    Thing mihome:sensor_motion:158d0001XXXXXX "Bedroom Motion" [itemId="158d0001XXXXXX"]

    Thing mihome:sensor_ht:158d0001XXXXXX "Bedroom Temperature" [itemId="158d0001XXXXXX"]
}
```

But there's this redundant "itemId" parameter. Do you think we could get rid of it? 
It's basically the same as the Thing ID.

Also, Bridge's serialNumber parameter is equal to its ID.


I will improve the README with textual config of Things and Bridge + add some battery item examples to the docs as well.
Then I think we'll be good to merge it @pboos.

Hadn't have a chance to test wired switches, but I encourage others to do that :)

Thank you again for all the dedication!

**Comment by kubawolanin** [comment]
@dimalo Please review my change 6ddd257 in README.md file. Pretty straightforward 😄 
Cheers!

**Comment by dimalo** [comment]
looks good to me. added yome minor things too and created a little PR...
please check if the 86sw work again. I think I found it.

**Comment by kubawolanin** [comment]
@dimalo 86sw works great. I didn't encounter any problems with the binding.
Thank you for your fixes!

@dimalo @pboos shall we merge this PR already?

**Comment by pboos** [comment]
@kubawolanin sounds good to me :).
@dimalo give me a heads up and i will merge it :)

**Comment by dimalo** [comment]
I'm happy with it.
Some minor things to test:
New devices (if they arrive...)
Multi gateway
I enhanced the handling of messages, so that every bridge is recognized by its IP and only the appropriate listeners (devices connected to the bridge) are notified, this is working with one bridge, I don't expect any difficulties here. The way from OH to devices I was not able to check though. For example switch plugs connected to different bridges...
For that we need the crowd, as the basic stuff is working well.
What do you think, should we rename the new batteryLevel (new value 0-100%) channel to something, which is not getting mixed up with the former batteryLevel trigger channel?

**Comment by pboos** [comment]
merged and pushed upstream now :) hope it will get merged in soon! thx for all the work!!!!

**Pull request merged**
