### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by dimalo**
finally requesting the cherry picked commit...
here's the original comment:

> periodic heartbeat was taken as report, so devices all of a sudden changed status, even if nothing was triggered.
> also modified bridge handler to update device online status from heartbeat - not sure if this is done right, please have a look!
> cheers

### CODE REVIEW

**Comment by arkserg** [comment]
Hi @dimalo ! It looks like that your PR covers my problem to, so I will take back my PR :)

**Comment by dimalo** [comment]
Hey @arkserg, have a try - hope it works well, for me it does :)
Thanks to your PR I had no big overhead finding my problem

**Comment by dimalo** [comment]
another one:
the user can change the delay time for "no-motion"
Screenshot

**Comment by hamwong** [comment]
do you mind share the newest mihome snapshot? I can't found anywhere to download the jar

**Comment by dimalo** [comment]
Have a look on my recent comment in the pull request discussion for the openhab repo...

**Comment by hamwong** [comment]
I really have no idea how to directly get individual addon jar from github, I've been look around in openhab community and here for many days without result.  URL link or quick guide will be appreciated.

**Comment by dimalo** [comment]
https://github.com/openhab/openhab2-addons/files/852333/org.openhab.binding.mihome-2.1.0-SNAPSHOT.jar.zip

**Comment by hamwong** [comment]
Huge Thanks

**Comment by pboos** [comment]
Sorry it took me so long. Just went over it quickly. Looks pretty okay to me :)

**Comment by pboos** [comment]
I see you did quite some work. And nice that the pull request always gets updated when you add new code. So it should be on the newest version you had. Please commit a new pull request when you do something new :).
Sadly I can not yet test anything. I currently do not have my raspberry pi at home (because of moving).

**Pull request merged**
